version: "2"

issues:
  max-same-issues: 0

linters:
  default: all
  # enable:
  #   - govet # standard
  #   - errcheck # standard
  #   - staticcheck # standard
  #   - unused # standard
  #   - ineffassign # standard
  #   - misspell
  settings:
    nolintlint:
      require-explanation: false

  disable:
    - cyclop
    - depguard
    - err113
    - exhaustruct
    - funcorder
    - funlen
    - gochecknoglobals
    - gocognit
    - gocyclo
    - godoclint
    - godot
    - godox
    - gosmopolitan
    - lll
    - mnd
    - noinlineerr
    - paralleltest
    - revive
    - tagliatelle
    - unparam #maybe
    - varnamelen
    - wsl # deprecated use wsl_v5
    - wsl_v5

formatters:
  enable:
    - gofumpt
    - goimports
